---
# Source: bluecompute-ce/charts/mysql/templates/tests/test-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-mysql-test
  labels:
    app: inventory-mysql
data:
  run.sh: |-
    @test "Testing MySQL Connection" {
      mysql --host=inventory-mysql --port=3306 -u root -padmin123
    }
