apiVersion: v1
kind: Service
metadata:
  name: customer-couchdb-svc-couchdb
  labels:
    app: couchdb
spec:
  ports:
    - port: 5985
      protocol: TCP
      targetPort: 5984
  type: ClusterIP
  selector:
    app: couchdb
